# Generated by Django 3.1.4 on 2020-12-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Vategoria',
            },
        ),
    ]
