# Generated by Django 3.1.4 on 2021-01-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201230_0134'),
        ('user', '0003_auto_20201227_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pontos',
            new_name='total_pontos',
        ),
        migrations.AddField(
            model_name='profile',
            name='questao_corretas',
            field=models.ManyToManyField(blank=True, related_name='questao_corretas', to='quiz.Questao'),
        ),
        migrations.AddField(
            model_name='profile',
            name='questao_erradas',
            field=models.ManyToManyField(blank=True, related_name='questao_erradas', to='quiz.Questao'),
        ),
    ]
