# Generated by Django 3.1.4 on 2021-01-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210104_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sequencial',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
