# Generated by Django 3.1.4 on 2021-01-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_sequencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pontos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
